### ISSUE TITLE
get and downloadAllVideosFromUser only returning the most recent 30 videos?

### ISSUE THREAD

**Issue by aa1s2d** [naseif/tiktok-scraper#1]
Hi, the scraper works well! 

When I use the getAllVideosFromUser and downloadAllVideosFromUser methods, it only returns the 30 most recent videos from the profile.

Is there something I'm doing wrong, or is its a limitation imposed by the scraper/language/TikTok, or something else?

Thanks

**Comment by naseif** [comment]
Hey @aa1s2d,

unfortunately this is something that I can not change because of the way I am scraping the user page and it is actually my mistake that I have not mentioned this in the README. When I am scraping the user I immediately get the first 30 videos from the user page because this is what is available in that moment and you will be able to get the remaining videos only by interacting with page and clicking the more button. This can sure be done/achieved by using something like selenium or puppeteer to scrape the page with chrome and interact with page directly but this is not something I wanted to do because its not as fast as scraping the HTML content of the page and working with it.
