### ISSUE TITLE
Error JSON input

### ISSUE THREAD

**Issue by Mukclay** [naseif/tiktok-scraper#6]
can you help me in solving my problem?, I have a problem, namely SyntaxError: Unexpected end of JSON input

what should i do, i just learned about all of this

**Comment by HazimAr** [comment]
@naseif I looked into this and found that it isn't rereviewing all the data from the `SIGI-STATE` json. I think this is due to the size of the json object so when parsing through the html it doesn't show up all the way. I think the solution can be to grab this json straight from the request instead of parsing through the HTML. I might be able to create a pull request for this because I am in need of a nice well typed API like this one.

**Comment by HazimAr** [comment]
![image](https://user-images.githubusercontent.com/64544952/178851591-db366496-4467-4b7f-a350-eb68fe0ed9a7.png)

**Comment by naseif** [comment]
Try again with the new update.
